/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HomeRemediesService } from "../homeRemedies.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HomeRemediesCreateInput } from "./HomeRemediesCreateInput";
import { HomeRemedies } from "./HomeRemedies";
import { HomeRemediesFindManyArgs } from "./HomeRemediesFindManyArgs";
import { HomeRemediesWhereUniqueInput } from "./HomeRemediesWhereUniqueInput";
import { HomeRemediesUpdateInput } from "./HomeRemediesUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HomeRemediesControllerBase {
  constructor(
    protected readonly service: HomeRemediesService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HomeRemedies })
  @nestAccessControl.UseRoles({
    resource: "HomeRemedies",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createHomeRemedies(
    @common.Body() data: HomeRemediesCreateInput
  ): Promise<HomeRemedies> {
    return await this.service.createHomeRemedies({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        skinCondition: true,
        remedyDetails: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [HomeRemedies] })
  @ApiNestedQuery(HomeRemediesFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "HomeRemedies",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async homeRemediesItems(
    @common.Req() request: Request
  ): Promise<HomeRemedies[]> {
    const args = plainToClass(HomeRemediesFindManyArgs, request.query);
    return this.service.homeRemediesItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        skinCondition: true,
        remedyDetails: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HomeRemedies })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HomeRemedies",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async homeRemedies(
    @common.Param() params: HomeRemediesWhereUniqueInput
  ): Promise<HomeRemedies | null> {
    const result = await this.service.homeRemedies({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        skinCondition: true,
        remedyDetails: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HomeRemedies })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HomeRemedies",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateHomeRemedies(
    @common.Param() params: HomeRemediesWhereUniqueInput,
    @common.Body() data: HomeRemediesUpdateInput
  ): Promise<HomeRemedies | null> {
    try {
      return await this.service.updateHomeRemedies({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          skinCondition: true,
          remedyDetails: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HomeRemedies })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HomeRemedies",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteHomeRemedies(
    @common.Param() params: HomeRemediesWhereUniqueInput
  ): Promise<HomeRemedies | null> {
    try {
      return await this.service.deleteHomeRemedies({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          skinCondition: true,
          remedyDetails: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
