/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsEnum,
  IsDate,
  ValidateNested,
} from "class-validator";
import { EnumImagesAnalysisStatus } from "./EnumImagesAnalysisStatus";
import { Type } from "class-transformer";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { AnalysisResultsCreateNestedManyWithoutImagesItemsInput } from "./AnalysisResultsCreateNestedManyWithoutImagesItemsInput";
import { GoogleGeminiResultsCreateNestedManyWithoutImagesItemsInput } from "./GoogleGeminiResultsCreateNestedManyWithoutImagesItemsInput";

@InputType()
class ImagesCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  imageUrl?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumImagesAnalysisStatus,
  })
  @IsEnum(EnumImagesAnalysisStatus)
  @IsOptional()
  @Field(() => EnumImagesAnalysisStatus, {
    nullable: true,
  })
  analysisStatus?: "Option1" | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  uploadedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => AnalysisResultsCreateNestedManyWithoutImagesItemsInput,
  })
  @ValidateNested()
  @Type(() => AnalysisResultsCreateNestedManyWithoutImagesItemsInput)
  @IsOptional()
  @Field(() => AnalysisResultsCreateNestedManyWithoutImagesItemsInput, {
    nullable: true,
  })
  analysisResultsItems?: AnalysisResultsCreateNestedManyWithoutImagesItemsInput;

  @ApiProperty({
    required: false,
    type: () => GoogleGeminiResultsCreateNestedManyWithoutImagesItemsInput,
  })
  @ValidateNested()
  @Type(() => GoogleGeminiResultsCreateNestedManyWithoutImagesItemsInput)
  @IsOptional()
  @Field(() => GoogleGeminiResultsCreateNestedManyWithoutImagesItemsInput, {
    nullable: true,
  })
  googleGeminiResultsItems?: GoogleGeminiResultsCreateNestedManyWithoutImagesItemsInput;
}

export { ImagesCreateInput as ImagesCreateInput };
