/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsEnum,
  IsDate,
  ValidateNested,
} from "class-validator";
import { EnumImagesAnalysisStatus } from "./EnumImagesAnalysisStatus";
import { Type } from "class-transformer";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { AnalysisResultsUpdateManyWithoutImagesItemsInput } from "./AnalysisResultsUpdateManyWithoutImagesItemsInput";
import { GoogleGeminiResultsUpdateManyWithoutImagesItemsInput } from "./GoogleGeminiResultsUpdateManyWithoutImagesItemsInput";

@InputType()
class ImagesUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  imageUrl?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumImagesAnalysisStatus,
  })
  @IsEnum(EnumImagesAnalysisStatus)
  @IsOptional()
  @Field(() => EnumImagesAnalysisStatus, {
    nullable: true,
  })
  analysisStatus?: "Option1" | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  uploadedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => AnalysisResultsUpdateManyWithoutImagesItemsInput,
  })
  @ValidateNested()
  @Type(() => AnalysisResultsUpdateManyWithoutImagesItemsInput)
  @IsOptional()
  @Field(() => AnalysisResultsUpdateManyWithoutImagesItemsInput, {
    nullable: true,
  })
  analysisResultsItems?: AnalysisResultsUpdateManyWithoutImagesItemsInput;

  @ApiProperty({
    required: false,
    type: () => GoogleGeminiResultsUpdateManyWithoutImagesItemsInput,
  })
  @ValidateNested()
  @Type(() => GoogleGeminiResultsUpdateManyWithoutImagesItemsInput)
  @IsOptional()
  @Field(() => GoogleGeminiResultsUpdateManyWithoutImagesItemsInput, {
    nullable: true,
  })
  googleGeminiResultsItems?: GoogleGeminiResultsUpdateManyWithoutImagesItemsInput;
}

export { ImagesUpdateInput as ImagesUpdateInput };
