/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsDate,
  MaxLength,
  IsOptional,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumImagesAnalysisStatus } from "./EnumImagesAnalysisStatus";
import { User } from "../../user/base/User";
import { AnalysisResults } from "../../analysisResults/base/AnalysisResults";
import { GoogleGeminiResults } from "../../googleGeminiResults/base/GoogleGeminiResults";

@ObjectType()
class Images {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  imageUrl!: string | null;

  @ApiProperty({
    required: false,
    enum: EnumImagesAnalysisStatus,
  })
  @IsEnum(EnumImagesAnalysisStatus)
  @IsOptional()
  @Field(() => EnumImagesAnalysisStatus, {
    nullable: true,
  })
  analysisStatus?: "Option1" | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  uploadedAt!: Date | null;

  @ApiProperty({
    required: false,
    type: () => User,
  })
  @ValidateNested()
  @Type(() => User)
  @IsOptional()
  user?: User | null;

  @ApiProperty({
    required: false,
    type: () => [AnalysisResults],
  })
  @ValidateNested()
  @Type(() => AnalysisResults)
  @IsOptional()
  analysisResultsItems?: Array<AnalysisResults>;

  @ApiProperty({
    required: false,
    type: () => [GoogleGeminiResults],
  })
  @ValidateNested()
  @Type(() => GoogleGeminiResults)
  @IsOptional()
  googleGeminiResultsItems?: Array<GoogleGeminiResults>;
}

export { Images as Images };
