/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { EnumImagesAnalysisStatus } from "./EnumImagesAnalysisStatus";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { AnalysisResultsListRelationFilter } from "../../analysisResults/base/AnalysisResultsListRelationFilter";
import { GoogleGeminiResultsListRelationFilter } from "../../googleGeminiResults/base/GoogleGeminiResultsListRelationFilter";

@InputType()
class ImagesWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  imageUrl?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumImagesAnalysisStatus,
  })
  @IsEnum(EnumImagesAnalysisStatus)
  @IsOptional()
  @Field(() => EnumImagesAnalysisStatus, {
    nullable: true,
  })
  analysisStatus?: "Option1";

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  uploadedAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => AnalysisResultsListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AnalysisResultsListRelationFilter)
  @IsOptional()
  @Field(() => AnalysisResultsListRelationFilter, {
    nullable: true,
  })
  analysisResultsItems?: AnalysisResultsListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => GoogleGeminiResultsListRelationFilter,
  })
  @ValidateNested()
  @Type(() => GoogleGeminiResultsListRelationFilter)
  @IsOptional()
  @Field(() => GoogleGeminiResultsListRelationFilter, {
    nullable: true,
  })
  googleGeminiResultsItems?: GoogleGeminiResultsListRelationFilter;
}

export { ImagesWhereInput as ImagesWhereInput };
