/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { GoogleGeminiResultsService } from "../googleGeminiResults.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GoogleGeminiResultsCreateInput } from "./GoogleGeminiResultsCreateInput";
import { GoogleGeminiResults } from "./GoogleGeminiResults";
import { GoogleGeminiResultsFindManyArgs } from "./GoogleGeminiResultsFindManyArgs";
import { GoogleGeminiResultsWhereUniqueInput } from "./GoogleGeminiResultsWhereUniqueInput";
import { GoogleGeminiResultsUpdateInput } from "./GoogleGeminiResultsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class GoogleGeminiResultsControllerBase {
  constructor(
    protected readonly service: GoogleGeminiResultsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: GoogleGeminiResults })
  @nestAccessControl.UseRoles({
    resource: "GoogleGeminiResults",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createGoogleGeminiResults(
    @common.Body() data: GoogleGeminiResultsCreateInput
  ): Promise<GoogleGeminiResults> {
    return await this.service.createGoogleGeminiResults({
      data: {
        ...data,

        image: data.image
          ? {
              connect: data.image,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        geminiResult: true,

        image: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [GoogleGeminiResults] })
  @ApiNestedQuery(GoogleGeminiResultsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "GoogleGeminiResults",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async googleGeminiResultsItems(
    @common.Req() request: Request
  ): Promise<GoogleGeminiResults[]> {
    const args = plainToClass(GoogleGeminiResultsFindManyArgs, request.query);
    return this.service.googleGeminiResultsItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        geminiResult: true,

        image: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: GoogleGeminiResults })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GoogleGeminiResults",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async googleGeminiResults(
    @common.Param() params: GoogleGeminiResultsWhereUniqueInput
  ): Promise<GoogleGeminiResults | null> {
    const result = await this.service.googleGeminiResults({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        geminiResult: true,

        image: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: GoogleGeminiResults })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GoogleGeminiResults",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateGoogleGeminiResults(
    @common.Param() params: GoogleGeminiResultsWhereUniqueInput,
    @common.Body() data: GoogleGeminiResultsUpdateInput
  ): Promise<GoogleGeminiResults | null> {
    try {
      return await this.service.updateGoogleGeminiResults({
        where: params,
        data: {
          ...data,

          image: data.image
            ? {
                connect: data.image,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          geminiResult: true,

          image: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: GoogleGeminiResults })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GoogleGeminiResults",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteGoogleGeminiResults(
    @common.Param() params: GoogleGeminiResultsWhereUniqueInput
  ): Promise<GoogleGeminiResults | null> {
    try {
      return await this.service.deleteGoogleGeminiResults({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          geminiResult: true,

          image: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
