/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ConsultationsService } from "../consultations.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ConsultationsCreateInput } from "./ConsultationsCreateInput";
import { Consultations } from "./Consultations";
import { ConsultationsFindManyArgs } from "./ConsultationsFindManyArgs";
import { ConsultationsWhereUniqueInput } from "./ConsultationsWhereUniqueInput";
import { ConsultationsUpdateInput } from "./ConsultationsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ConsultationsControllerBase {
  constructor(
    protected readonly service: ConsultationsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Consultations })
  @nestAccessControl.UseRoles({
    resource: "Consultations",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createConsultations(
    @common.Body() data: ConsultationsCreateInput
  ): Promise<Consultations> {
    return await this.service.createConsultations({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        dateTime: true,
        status: true,
        notes: true,
        patient: true,
        doctor: true,
        facility: true,
        doctorName: true,
        contactInfo: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Consultations] })
  @ApiNestedQuery(ConsultationsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Consultations",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async consultationsItems(
    @common.Req() request: Request
  ): Promise<Consultations[]> {
    const args = plainToClass(ConsultationsFindManyArgs, request.query);
    return this.service.consultationsItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        dateTime: true,
        status: true,
        notes: true,
        patient: true,
        doctor: true,
        facility: true,
        doctorName: true,
        contactInfo: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Consultations })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Consultations",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async consultations(
    @common.Param() params: ConsultationsWhereUniqueInput
  ): Promise<Consultations | null> {
    const result = await this.service.consultations({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        dateTime: true,
        status: true,
        notes: true,
        patient: true,
        doctor: true,
        facility: true,
        doctorName: true,
        contactInfo: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Consultations })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Consultations",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateConsultations(
    @common.Param() params: ConsultationsWhereUniqueInput,
    @common.Body() data: ConsultationsUpdateInput
  ): Promise<Consultations | null> {
    try {
      return await this.service.updateConsultations({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          dateTime: true,
          status: true,
          notes: true,
          patient: true,
          doctor: true,
          facility: true,
          doctorName: true,
          contactInfo: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Consultations })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Consultations",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteConsultations(
    @common.Param() params: ConsultationsWhereUniqueInput
  ): Promise<Consultations | null> {
    try {
      return await this.service.deleteConsultations({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          dateTime: true,
          status: true,
          notes: true,
          patient: true,
          doctor: true,
          facility: true,
          doctorName: true,
          contactInfo: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
